const allTires = [
  // Lawn tires
  {
    id: 'l1',
    brand: 'Carlisle',
    size: '15x6.00-6',
    price: 45.99,
    image: '/images/tires/lawn-tire-generic.jpg',
    description: 'Known for turf-friendly treads and durability',
    category: 'lawn',
    stock: 15,
    position: null,
  },
  {
    id: 'l2',
    brand: 'Carlisle',
    size: '20x10.00-8',
    price: 65.99,
    image: '/images/tires/lawn-tire-generic.jpg',
    description: 'Known for turf-friendly treads and durability',
    category: 'lawn',
    stock: 12,
    position: null,
  },
  {
    id: 'l3',
    brand: 'Carlisle',
    size: '18x9.50-8',
    price: 58.99,
    image: '/images/tires/lawn-tire-generic.jpg',
    description: 'Known for turf-friendly treads and durability',
    category: 'lawn',
    stock: 10,
    position: null,
  },
  {
    id: 'l4',
    brand: 'Kenda',
    size: '13x5.00-6',
    price: 38.99,
    image: '/images/tires/lawn-tire-generic.jpg',
    description: 'Affordable and widely available',
    category: 'lawn',
    stock: 20,
    position: null,
  },
  {
    id: 'l5',
    brand: 'Kenda',
    size: '16x6.50-8',
    price: 48.99,
    image: '/images/tires/lawn-tire-generic.jpg',
    description: 'Affordable and widely available',
    category: 'lawn',
    stock: 18,
    position: null,
  },
  {
    id: 'l6',
    brand: 'Kenda',
    size: '18x8.50-8',
    price: 55.99,
    image: '/images/tires/lawn-tire-generic.jpg',
    description: 'Affordable and widely available',
    category: 'lawn',
    stock: 14,
    position: null,
  },
  {
    id: 'l7',
    brand: 'MaxAuto',
    size: '15x6.00-6',
    price: 42.99,
    image: '/images/tires/lawn-tire-generic.jpg',
    description: 'Popular on Amazon, good for replacements',
    category: 'lawn',
    stock: 16,
    position: null,
  },
  {
    id: 'l8',
    brand: 'MaxAuto',
    size: '20x10.00-8',
    price: 62.99,
    image: '/images/tires/lawn-tire-generic.jpg',
    description: 'Popular on Amazon, good for replacements',
    category: 'lawn',
    stock: 11,
    position: null,
  },
  {
    id: 'l9',
    brand: 'Deestone',
    size: '13x5.00-6',
    price: 35.99,
    image: '/images/tires/lawn-tire-generic.jpg',
    description: 'Budget-friendly, decent for light-duty',
    category: 'lawn',
    stock: 22,
    position: null,
  },
  {
    id: 'l10',
    brand: 'Deestone',
    size: '18x9.50-8',
    price: 52.99,
    image: '/images/tires/lawn-tire-generic.jpg',
    description: 'Budget-friendly, decent for light-duty',
    category: 'lawn',
    stock: 13,
    position: null,
  },
  {
    id: 'l11',
    brand: 'Hi-Run',
    size: '16x6.50-8',
    price: 46.99,
    image: '/images/tires/lawn-tire-generic.jpg',
    description: 'OEM replacement for many riding mowers',
    category: 'lawn',
    stock: 17,
    position: null,
  },
  {
    id: 'l12',
    brand: 'Hi-Run',
    size: '20x8.00-8',
    price: 59.99,
    image: '/images/tires/lawn-tire-generic.jpg',
    description: 'OEM replacement for many riding mowers',
    category: 'lawn',
    stock: 9,
    position: null,
  },
  {
    id: 'l13',
    brand: 'Wanda',
    size: '15x6.00-6',
    price: 44.99,
    image: '/images/tires/lawn-tire-generic.jpg',
    description: 'Good grip and value for turf tires',
    category: 'lawn',
    stock: 19,
    position: null,
  },
  {
    id: 'l14',
    brand: 'Wanda',
    size: '18x9.50-8',
    price: 56.99,
    image: '/images/tires/lawn-tire-generic.jpg',
    description: 'Good grip and value for turf tires',
    category: 'lawn',
    stock: 15,
    position: null,
  },

  // Motorcycle tires
  {
    id: 'm1',
    brand: 'Michelin',
    size: '120/70ZR17',
    position: 'Front',
    price: 189.99,
    image: '/images/tires/michelin-motorcycle-tire.jpg',
    description: 'Pilot Road series - great all-rounder',
    category: 'motorcycle',
    stock: 8,
  },
  {
    id: 'm2',
    brand: 'Michelin',
    size: '180/55ZR17',
    position: 'Rear',
    price: 229.99,
    image: '/images/tires/lawn-tire-generic.jpg',
    description: 'Power series - great all-rounder',
    category: 'motorcycle',
    stock: 7,
  },
  {
    id: 'm3',
    brand: 'Pirelli',
    size: '110/70-17',
    position: 'Front',
    price: 179.99,
    image: '/images/tires/lawn-tire-generic.jpg',
    description: 'Diablo Rosso - sporty and grippy',
    category: 'motorcycle',
    stock: 10,
  },
  {
    id: 'm4',
    brand: 'Pirelli',
    size: '160/60-17',
    position: 'Rear',
    price: 219.99,
    image: '/images/tires/lawn-tire-generic.jpg',
    description: 'Angel GT - sporty and grippy',
    category: 'motorcycle',
    stock: 9,
  },
  {
    id: 'm5',
    brand: 'Dunlop',
    size: '100/90-19',
    position: 'Front',
    price: 159.99,
    image: '/images/tires/lawn-tire-generic.jpg',
    description: 'OEM on many cruisers and sportbikes',
    category: 'motorcycle',
    stock: 12,
  },
  {
    id: 'm6',
    brand: 'Dunlop',
    size: '150/80-16',
    position: 'Rear',
    price: 185.99,
    image: '/images/tires/lawn-tire-generic.jpg',
    description: 'OEM on many cruisers and sportbikes',
    category: 'motorcycle',
    stock: 11,
  },
  {
    id: 'm7',
    brand: 'Metzeler',
    size: '120/70ZR17',
    position: 'Front',
    price: 195.99,
    image: '/images/tires/lawn-tire-generic.jpg',
    description: 'Sportec series - touring and sport',
    category: 'motorcycle',
    stock: 6,
  },
  {
    id: 'm8',
    brand: 'Metzeler',
    size: '180/55ZR17',
    position: 'Rear',
    price: 239.99,
    image: '/images/tires/lawn-tire-generic.jpg',
    description: 'ME series - touring and sport',
    category: 'motorcycle',
    stock: 5,
  },
  {
    id: 'm9',
    brand: 'Shinko',
    size: '130/90-16',
    position: 'Rear',
    price: 119.99,
    image: '/images/tires/lawn-tire-generic.jpg',
    description: 'Budget-friendly, decent performance',
    category: 'motorcycle',
    stock: 15,
  },
  {
    id: 'm10',
    brand: 'Shinko',
    size: '170/80-15',
    position: 'Rear',
    price: 129.99,
    image: '/images/tires/lawn-tire-generic.jpg',
    description: 'Budget-friendly, decent performance',
    category: 'motorcycle',
    stock: 13,
  },
  {
    id: 'm11',
    brand: 'Avon',
    size: '90/90-21',
    position: 'Front',
    price: 149.99,
    image: '/images/tires/lawn-tire-generic.jpg',
    description: 'Great for cruisers and customs',
    category: 'motorcycle',
    stock: 14,
  },
  {
    id: 'm12',
    brand: 'Avon',
    size: '150/80-16',
    position: 'Rear',
    price: 179.99,
    image: '/images/tires/lawn-tire-generic.jpg',
    description: 'Great for cruisers and customs',
    category: 'motorcycle',
    stock: 12,
  },
];

exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('tires').del();

  // Inserts seed entries
  await knex('tires').insert(allTires);
};
